# Default values for deel-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 5
namespace: deel-app
image:
  repository: 324037298804.dkr.ecr.us-east-1.amazonaws.com/deel-test-registry
  tag: 88b268b
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
strategy:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 10
container:
  name: deel-app
  port: 8080
ingress:
  enabled: false
  hosts:
    - host: deel.gabapp.tech
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
