# Default values for deel-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
namespace: deel-app
image:
  repository: 324037298804.dkr.ecr.us-east-1.amazonaws.com/deel-test-registry
  tag: b57a6bf
  pullPolicy: Always

service:
  type: LoadBalancer
  port: "80" # Port value as a string
  targetPort: "8080" # Target port value as a string

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 5

container:
  name: deel-app
  port: "8080" # Container port as a string

ingress:
  enabled: false
  hosts:
    - host: deel.gabapp.tech
      paths:
        - path: "/"
          pathType: ImplementationSpecific
