apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deel-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/pilotgab/gabriel-deel-tech-assignment.git"
    path: ./deel-test
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: "deel-test"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
