apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deel-app
  namespace: argocd
spec:
  destination:
    namespace: deel-app
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/pilotgab/gabriel-deel-tech-assignment.git
    path: ./deel-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
