apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.container.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
      maxSurge: {{ .Values.strategy.maxSurge }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      # Optional: Uncomment this section if you want to manage autoscaling within the deployment.
      # autoscaling:
      #   enabled: {{ .Values.autoscaling.enabled }}
      #   minReplicas: {{ .Values.autoscaling.minReplicas }}
      #   maxReplicas: {{ .Values.autoscaling.maxReplicas }}
      #   targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
