# Default values for deel-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: 476338596483.dkr.ecr.eu-west-1.amazonaws.com/deel-test-registry
  tag: 76f5363
  pullPolicy: Always


service:
  type: LoadBalancer
  port: 80
  targetPort:
    port: 8080


resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"


autoscaling:
  enabled: false
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 4

container:
  name: deel-test
  port: 8080
