# Default values for deel-test.
# This is a YAML-formatted file.
# values
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: 324037298804.dkr.ecr.us-east-1.amazonaws.com/deel-test-registry
  tag: dce1b67
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 10

container:
  name: deel-test
  port: 8080
